services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CarstenWalther\Html2pdf\Middleware\Output:
    public: true
    arguments:
      $responseFactory: '@Psr\Http\Message\ResponseFactoryInterface'
      $requestFactory: '@Psr\Http\Message\RequestFactoryInterface'

  CarstenWalther\Html2pdf\:
    resource: '../Classes/*'
    exclude: '../Classes/Report'

  CarstenWalther\Html2pdf\Report\ExtensionStatus:
    tags:
      - name: reports.status